### ISSUE TITLE
When to release the models’ weights

### ISSUE THREAD

**Issue by 9p15p** [Tanveer81/BoxVOS#1]
Hi, Thanks for your great work.
Would you please upload the weights of your model.
Thank you.

**Comment by Tanveer81** [comment]
I have added the [weights](https://syncandshare.lrz.de/getlink/fiW3kjxv4XB6KvrXVVXCAMBn/) in README.md

**Comment by 9p15p** [comment]
Hi, this link is unstable. Maybe Google Drive will work well. 

Thank you.

**Comment by Tanveer81** [comment]
Here is the Google Drive link. https://drive.google.com/drive/folders/1pQTSis8dLs08ZY2hb-YZR_B1GJlu52ju?usp=share_link
I also added it in Readme.md file.
